<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260503184503 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE billing_course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, type SMALLINT NOT NULL, price DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BILLING_COURSE_CODE ON billing_course (code)');
        $this->addSql('CREATE TABLE billing_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, value DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, course_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F5B3C16CA76ED395 ON billing_transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_F5B3C16C591CC992 ON billing_transaction (course_id)');
        $this->addSql('ALTER TABLE billing_transaction ADD CONSTRAINT FK_F5B3C16CA76ED395 FOREIGN KEY (user_id) REFERENCES "billing_user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_transaction ADD CONSTRAINT FK_F5B3C16C591CC992 FOREIGN KEY (course_id) REFERENCES billing_course (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE billing_transaction DROP CONSTRAINT FK_F5B3C16CA76ED395');
        $this->addSql('ALTER TABLE billing_transaction DROP CONSTRAINT FK_F5B3C16C591CC992');
        $this->addSql('DROP TABLE billing_course');
        $this->addSql('DROP TABLE billing_transaction');
    }
}
